title = "Lewis Denham-Parry"
description= "A few years ago, while visiting or, rather, rummaging about Notre-Dame, the author of this book found, in an obscure nook of one of the towers, the following word, engraved by hand upon the wall: â€”ANANKE."
baseURL = "https://denhamparry.netlify.com"
languageCode = "en-gb"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = "UA-33113860-1"
disqusShortname = "denhamparry"
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "favicon.ico"
  title = ""
  description = "Random posts from Lewis Denham-Parry."
  # facebook = "https://facebook.com/denhamparry"
  twitter = "https://twitter.com/denhamparry"
  instagram = "https://www.instagram.com/denhamparry/"
  # youtube = "https://www.youtube.com/channel/UCBFyX1n9CbySYTsdsPei8aA"
  github = "https://github.com/denhamparry"
  # gitlab = "https://gitlab.com/denhamparry"
  linkedin = "https://www.linkedin.com/in/denhamparry/"
  background_color_class = "bg-moon-grey"
  featured_image = "images/landing/landing00.png"
  recent_posts_number = 9
  show_reading_time = true