baseURL: "https://denhamparry.co.uk"
title: "Lewis Denham-Parry"
theme: PaperMod

pagination:
  pagerSize: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: G-SNNE5MMPPC

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  description: "The life and times of Lewis Denham-Parry"
  defaultTheme: dark
  showBreadCrumbs: false
  profileMode:
    enabled: true
    title: "Did somebody say üç∞"
  socialIcons:
    - name: github
      url: "https://github.com/denhamparry"
    - name: linkedin
      url: "https://www.linkedin.com/in/denhamparry/"
    - name: cv
      url: "https://edera.dev"

privacy:
  x:
    disabled: false
    enableDNT: true
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
