baseURL = "https://denhamparry.co.uk"
languageCode = "en-gb"
defaultContentLanguage = "en"
title = "Lewis Denham-Parry"
theme = "tale"

rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  
googleAnalytics = "UA-33113860-1"

[author]
  name = "Lewis Denham-Parry"

[params]
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "01-02-2006"
  dateformNumTime = "2006-01-02 15:04 -0700"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0
